version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.18
    steps:
      - checkout
      - run:
          name: Install deps
          command: yarn --cwd frontend/ install
      - run:
          name: Run tests
          command: yarn --cwd frontend/ test

workflows:
  build-and-test:
    jobs:
      - build-and-test
